### ISSUE TITLE
Self code review

### ISSUE THREAD

**Issue by utubo** [utubo/firefox-simple_gesture#24]

**Comment by utubo** [comment]
いったんクローズ

**Comment by utubo** [comment]
options.js L404-L407
``` javascript
const setupSettingItems = res => {
		if (res && res.simple_gesture) {
			SimpleGesture.ini = res.simple_gesture;
}
```

**Comment by utubo** [comment]
options.js L175
delete this line.
```javascript
b.classList.remove('hide');
```

**Comment by utubo** [comment]
options.css L18
Title's padding is may be 0.8em.
```css
.title {
	background: #f2f2f2;
	border-bottom: 2px solid #0099ff;
	font-weight: bold;
	padding: 1em; ←HERE
}
```
